# Generated by Django 4.0.5 on 2022-06-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор мема'),
        ),
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Число лайков'),
        ),
    ]
