# Generated by Django 4.0.5 on 2022-06-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_meme_author_meme_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='photo',
            field=models.URLField(verbose_name='Мем'),
        ),
    ]
