# Generated by Django 4.0.5 on 2022-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_meme_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=True, verbose_name='Лайкнут (или пропущен)'),
        ),
    ]
